BUTTONS = {
    "Up": {"name": "Up", "keycode": "KEYCODE_DPAD_UP", "icon": "up.svg", "repeat": True},
    "Down": {"name": "Down", "keycode": "KEYCODE_DPAD_DOWN", "icon": "down.svg", "repeat": True},
    "Left": {"name": "Left", "keycode": "KEYCODE_DPAD_LEFT", "icon": "left.svg", "repeat": True},
    "Right": {"name": "Right", "keycode": "KEYCODE_DPAD_RIGHT", "icon": "right.svg", "repeat": True},
    "Select": {"name": "Select", "keycode": "KEYCODE_DPAD_CENTER", "icon": "select.svg", "repeat": False},
    "Back": {"name": "Back", "keycode": "KEYCODE_BACK", "icon": "back.svg", "repeat": False},
    "Home": {"name": "Home", "keycode": "KEYCODE_HOME", "icon": "home.svg", "repeat": False},
    "Menu": {"name": "Menu", "keycode": "KEYCODE_MENU", "icon": "menu.svg", "repeat": False},
    "Rewind": {"name": "Rewind", "keycode": "KEYCODE_MEDIA_REWIND", "icon": "rewind.svg", "repeat": False},
    "PlayPause": {"name": "Play / Pause", "keycode": "KEYCODE_MEDIA_PLAY_PAUSE", "icon": "playpause.svg", "repeat": False},
    "FastForward": {"name": "Fast Forward", "keycode": "KEYCODE_MEDIA_FAST_FORWARD", "icon": "fastforward.svg", "repeat": False},
    "Mute": {"name": "Mute", "keycode": "KEYCODE_VOLUME_MUTE", "icon": "mute.svg", "repeat": False},
    "VolumeUp": {"name": "Volume Up", "keycode": "KEYCODE_VOLUME_UP", "icon": "volumeup.svg", "repeat": True},
    "VolumeDown": {"name": "Volume Down", "keycode": "KEYCODE_VOLUME_DOWN", "icon": "volumedown.svg", "repeat": True},
    "Guide": {"name": "Guide", "keycode": "KEYCODE_GUIDE", "icon": "guide.svg", "repeat": False},
    "Power": {"name": "Power", "keycode": "KEYCODE_POWER", "icon": "power.svg", "repeat": False},
    "VoiceAssist": {"name": "Alexa / Voice Assist", "keycode": "KEYCODE_VOICE_ASSIST", "icon": "voice.svg", "repeat": False},
    "LiveTV": {"name": "Live TV / Guide", "keycode": "KEYCODE_GUIDE", "icon": "tv.svg", "repeat": False},
    "Info": {"name": "Info", "keycode": "KEYCODE_INFO", "icon": "info.svg", "repeat": False},
    "InputSelect": {"name": "Input Select", "keycode": "KEYCODE_TV_INPUT", "icon": "input.svg", "repeat": False},
    "InputHDMI1": {"name": "Input: HDMI 1", "keycode": "KEYCODE_TV_INPUT_HDMI_1", "icon": "hdmi1.svg", "repeat": False},
    "InputHDMI2": {"name": "Input: HDMI 2", "keycode": "KEYCODE_TV_INPUT_HDMI_2", "icon": "hdmi2.svg", "repeat": False},
    "InputHDMI3": {"name": "Input: HDMI 3", "keycode": "KEYCODE_TV_INPUT_HDMI_3", "icon": "hdmi3.svg", "repeat": False},
    "InputHDMI4": {"name": "Input: HDMI 4", "keycode": "KEYCODE_TV_INPUT_HDMI_4", "icon": "hdmi4.svg", "repeat": False},
    "InputAntennaCable": {"name": "Input: Antenna / Cable", "keycode": "KEYCODE_TV_ANTENNA_CABLE", "icon": "antenna.svg", "repeat": False},
    "InputComposite1": {"name": "Input: Composite 1", "keycode": "KEYCODE_TV_INPUT_COMPOSITE_1", "icon": "composite1.svg", "repeat": False},
    "InputComposite2": {"name": "Input: Composite 2", "keycode": "KEYCODE_TV_INPUT_COMPOSITE_2", "icon": "composite2.svg", "repeat": False},
    "InputComponent1": {"name": "Input: Component 1", "keycode": "KEYCODE_TV_INPUT_COMPONENT_1", "icon": "component1.svg", "repeat": False},
    "InputComponent2": {"name": "Input: Component 2", "keycode": "KEYCODE_TV_INPUT_COMPONENT_2", "icon": "component2.svg", "repeat": False},
    "InputVGA1": {"name": "Input: VGA 1", "keycode": "KEYCODE_TV_INPUT_VGA_1", "icon": "vga1.svg", "repeat": False},
}
